In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Data split
from sklearn.model_selection import train_test_split

# Models
from sklearn.ensemble import RandomForestClassifier

# Reports
from sklearn.metrics import accuracy_score, classification_report

In [16]:
data = pd.read_csv('preprocessed_data/dataset.csv')
data

,age,gender,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,...,employment_status_student,employment_status_unemployed,smoking_status_current,smoking_status_former,smoking_status_never,diabetes_stage_gestational,diabetes_stage_no_diabetes,diabetes_stage_pre_diabetes,diabetes_stage_type_1,diabetes_stage_type_2
0,58,0.0,0,215,5.7,7.9,7.9,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,48,1.0,1,143,6.7,6.5,8.7,0,0,0,...,0,0,0,1,0,0,1,0,0,0
2,60,0.0,1,57,6.4,10.0,8.1,1,0,0,...,0,1,0,0,1,0,0,0,0,1
3,74,1.0,0,49,3.4,6.6,5.2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,46,0.0,1,109,7.2,7.4,5.0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,1,136,8.3,6.4,4.5,0,0,0,...,0,1,0,1,0,0,0,1,0,0
99996,41,1.0,3,76,8.8,6.8,4.8,0,0,0,...,0,0,0,0,1,0,0,1,0,0
99997,57,1.0,4,121,9.9,5.0,6.1,0,0,1,...,0,0,0,1,0,0,1,0,0,0
99998,47,1.0,3,52,5.9,6.7,0.5,0,1,0,...,0,0,0,0,1,0,0,1,0,0
99999,52,1.0,1,248,2.7,5.4,5.5,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [17]:
# Split dataset - 80K rows for model training and 20K for prediction and comparison
last_20_k = data.tail(20000)
data = data.iloc[:-20000]

In [18]:
X = data.drop(columns='target')
y = data['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2)

In [19]:
model = RandomForestClassifier(
    n_estimators=50,
    max_depth=2
)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, n_estimators=50)

In [20]:
model.score(X_test, y_test)

0.999625

In [21]:
y_pred = model.predict(X_test)

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6412
           1       1.00      1.00      1.00      9588

    accuracy                           1.00     16000
   macro avg       1.00      1.00      1.00     16000
weighted avg       1.00      1.00      1.00     16000

In [23]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X, y, cv=5)
print(scores.mean())

0.999475

In [24]:
last_20_k

,age,gender,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,...,employment_status_student,employment_status_unemployed,smoking_status_current,smoking_status_former,smoking_status_never,diabetes_stage_gestational,diabetes_stage_no_diabetes,diabetes_stage_pre_diabetes,diabetes_stage_type_1,diabetes_stage_type_2
80000,61,1.0,3,293,8.5,6.9,5.4,0,0,0,...,1,0,1,0,0,0,0,1,0,0
80001,45,1.0,1,99,6.5,7.1,7.2,0,0,0,...,0,0,1,0,0,0,0,0,0,1
80002,49,1.0,1,101,6.4,10.0,6.5,0,1,0,...,0,0,0,1,0,0,0,0,0,1
80003,47,0.0,0,188,9.9,7.0,6.7,0,0,0,...,0,0,0,1,0,0,0,1,0,0
80004,58,0.0,0,43,7.6,6.6,0.5,0,0,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,1,136,8.3,6.4,4.5,0,0,0,...,0,1,0,1,0,0,0,1,0,0
99996,41,1.0,3,76,8.8,6.8,4.8,0,0,0,...,0,0,0,0,1,0,0,1,0,0
99997,57,1.0,4,121,9.9,5.0,6.1,0,0,1,...,0,0,0,1,0,0,1,0,0,0
99998,47,1.0,3,52,5.9,6.7,0.5,0,1,0,...,0,0,0,0,1,0,0,1,0,0
99999,52,1.0,1,248,2.7,5.4,5.5,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [25]:
# Split the dataset and separate the target column for later comparison with prediction results
X_last_20_k = last_20_k.drop(columns='target')
y_last_20_k = last_20_k['target']

In [26]:
prediction = model.predict(X_last_20_k)
prediction

array([0, 1, 1, ..., 0, 0, 0], shape=(20000,))

In [27]:
pred_dataframe = pd.DataFrame({
    'y_true': y_last_20_k,
    'y_pred': prediction
})

pred_dataframe.head()

       y_true  y_pred
80000       0       0
80001       1       1
80002       1       1
80003       0       0
80004       0       0

In [28]:
(pred_dataframe['y_true'] == pred_dataframe['y_pred']).mean()

np.float64(0.99965)